-- 코드를 입력하세요
SELECT CAR_TYPE, SUM(1) AS CARS
FROM CAR_RENTAL_COMPANY_CAR
WHERE 1 = 1
AND (
    FIND_IN_SET ('통풍시트', OPTIONS) > 0
 OR FIND_IN_SET ('열선시트', OPTIONS) > 0
 OR FIND_IN_SET ('가죽시트', OPTIONS) > 0
)
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE ASC;